### ISSUE TITLE
Publish Plugin to Grails 3 Plugins Repo

### ISSUE THREAD

**Issue by vsachinv** [JuNeHasIssues/grails-mailwatcher#1]
Hi @JuNeHasIssues 

Did you request to publish the plugin on Grails 3 repo? 
http://plugins.grails.org/

**Comment by JuNeHasIssues** [comment]
Hi!
Yes, I did two months ago but didn't get an answer yet. I will send a new one.

**Comment by JuNeHasIssues** [comment]
The plugin is now available on http://plugins.grails.org/plugin/junehasissues/grails-mailwatcher .
