### ISSUE TITLE
plugin support from reading attachments

### ISSUE THREAD

**Issue by menilub** [JuNeHasIssues/grails-mailwatcher#2]
Hi,
I need to read files sent to a specific account by email - in Grails 3 app
can I use this plugin - I don't see support from attachments

Thanks,
Meni

**Comment by JuNeHasIssues** [comment]
Hi Meni,

this plugin doesn't save attachments. It only provides the storage of all the properties mentioned in the email domain class. Storing attachments is a complicated matter and I haven't had the time to dig into it.

Have you found another solution for this problem? 

Best wishes!
